services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - 3002:3002
    env_file:
      - ../.env
    develop:
      watch:
        - path: ../package.json
          action: rebuild
        - path: ../src
          target: /home/app/src
          action: sync
    volumes:
      - type: bind
        source: ../
        target: /home/app
    networks:
      - edugreen
    links:
      - db
  db:
    image: mysql:latest
    restart: on-failure
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hola
      MYSQL_DATABASE: edugreen
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    tmpfs:
      - /var/run/mysqld
    volumes:
      - db_data:/var/lib/mysql
      - type: bind
        source: ../db
        target: /docker-entrypoint-initdb.d

networks:
  edugreen:
    external: true
volumes:
  db_data:
